"""add events table

Revision ID: b3385c003d3d
Revises: 39fc13495802
Create Date: 2026-07-24 22:31:40.404294

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'b3385c003d3d'
down_revision: str | None = '39fc13495802'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_name_occurred', 'events', ['name', 'occurred_at'], unique=False)
    op.create_index('ix_events_user_occurred', 'events', ['user_id', 'occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_user_occurred', table_name='events')
    op.drop_index('ix_events_name_occurred', table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
