"""add user role

Revision ID: 39fc13495802
Revises: e69658531c8e
Create Date: 2026-07-17 23:18:38.313754

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '39fc13495802'
down_revision: str | None = 'e69658531c8e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.Enum('job_seeker', 'recruiter', 'mix', name='userrole', native_enum=False, length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # ### end Alembic commands ###
