"""application status history

Revision ID: af849eece728
Revises: 49eaba48a68f
Create Date: 2026-07-24 22:53:21.924653

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = 'af849eece728'
down_revision: str | None = '49eaba48a68f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_status_history',
    sa.Column('application_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.Enum('saved', 'applied', 'in_review', 'recruiter_screen', 'technical_interview', 'test_task', 'final_interview', 'offer', 'rejected', 'withdrawn', 'ghosted', 'archived', name='applicationstatus', native_enum=False, length=32), nullable=True),
    sa.Column('to_status', sa.Enum('saved', 'applied', 'in_review', 'recruiter_screen', 'technical_interview', 'test_task', 'final_interview', 'offer', 'rejected', 'withdrawn', 'ghosted', 'archived', name='applicationstatus', native_enum=False, length=32), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['application_id'], ['applications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_application_status_history_application_id'), 'application_status_history', ['application_id'], unique=False)
    op.create_index('ix_application_status_history_application_id_changed_at', 'application_status_history', ['application_id', 'changed_at'], unique=False)
    op.create_index(op.f('ix_application_status_history_changed_at'), 'application_status_history', ['changed_at'], unique=False)
    op.create_index(op.f('ix_application_status_history_user_id'), 'application_status_history', ['user_id'], unique=False)
    # ### end Alembic commands ###

    # Backfill: seed one history row per live application (NULL -> current status),
    # dated at the application's creation time.
    op.execute(
        """
        INSERT INTO application_status_history
            (id, application_id, user_id, from_status, to_status, changed_at)
        SELECT gen_random_uuid(), id, user_id, NULL, status, created_at
        FROM applications
        WHERE deleted_at IS NULL
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_status_history_user_id'), table_name='application_status_history')
    op.drop_index(op.f('ix_application_status_history_changed_at'), table_name='application_status_history')
    op.drop_index('ix_application_status_history_application_id_changed_at', table_name='application_status_history')
    op.drop_index(op.f('ix_application_status_history_application_id'), table_name='application_status_history')
    op.drop_table('application_status_history')
    # ### end Alembic commands ###
