"""cv text extraction fields

Revision ID: 93c0f9f340da
Revises: af849eece728
Create Date: 2026-07-26 11:36:55.525190

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '93c0f9f340da'
down_revision: str | None = 'af849eece728'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # CVs uploaded before extraction existed are genuinely "pending", so the
    # server default backfills them. The default is kept, not dropped: migrations
    # run before the new code is live, and without it the previous app version
    # would fail every CV upload on a NOT NULL violation in that window.
    op.add_column('cv_versions', sa.Column('extraction_status', sa.Enum('pending', 'completed', 'failed', 'unsupported', name='cvextractionstatus', native_enum=False, length=32), nullable=False, server_default='pending'))
    op.add_column('cv_versions', sa.Column('extracted_text', sa.Text(), nullable=True))
    op.add_column('cv_versions', sa.Column('structured_content', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('cv_versions', sa.Column('extraction_error', sa.String(length=50), nullable=True))
    op.add_column('cv_versions', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.add_column('cv_versions', sa.Column('extracted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cv_versions', 'extracted_at')
    op.drop_column('cv_versions', 'content_hash')
    op.drop_column('cv_versions', 'extraction_error')
    op.drop_column('cv_versions', 'structured_content')
    op.drop_column('cv_versions', 'extracted_text')
    op.drop_column('cv_versions', 'extraction_status')
    # ### end Alembic commands ###
