"""career profile and onboarding state

Revision ID: ef6d5f4b243a
Revises: 93c0f9f340da
Create Date: 2026-07-26 17:43:43.270308

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'ef6d5f4b243a'
down_revision: str | None = '93c0f9f340da'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('profile_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('revision', sa.Integer(), server_default='0', nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_profiles_user_id'), 'career_profiles', ['user_id'], unique=True)
    op.add_column('users', sa.Column('onboarding_completed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('ai_consent_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###

    # Anyone who already picked a role finished the onboarding that existed when
    # they signed up. Without this they would be dropped back into the wizard on
    # their next visit; the career profile reaches them through the in-app
    # reminder instead, which is what a skippable step deserves.
    op.execute(
        "UPDATE users SET onboarding_completed_at = now() "
        "WHERE role IS NOT NULL AND onboarding_completed_at IS NULL"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ai_consent_at')
    op.drop_column('users', 'onboarding_completed_at')
    op.drop_index(op.f('ix_career_profiles_user_id'), table_name='career_profiles')
    op.drop_table('career_profiles')
    # ### end Alembic commands ###
