"""vacancy match analyses

Revision ID: c89c6adab935
Revises: ef6d5f4b243a
Create Date: 2026-07-26 20:39:32.365238

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'c89c6adab935'
down_revision: str | None = 'ef6d5f4b243a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancy_match_analyses',
    sa.Column('vacancy_id', sa.UUID(), nullable=False),
    sa.Column('cv_version_id', sa.UUID(), nullable=True),
    sa.Column('profile_revision', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('processing', 'completed', 'failed', name='matchstatus', native_enum=False, length=32), nullable=False),
    sa.Column('input_hash', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('verdict', sa.Enum('apply', 'maybe', 'skip', name='matchverdict', native_enum=False, length=32), nullable=True),
    sa.Column('confidence', sa.Enum('high', 'medium', 'low', name='matchconfidence', native_enum=False, length=32), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('next_action', sa.Enum('create_application', 'review_gaps', 'archive_vacancy', name='nextaction', native_enum=False, length=32), nullable=True),
    sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('matches', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gaps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('red_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('unknowns', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('prompt_version', sa.String(length=20), nullable=True),
    sa.Column('scoring_version', sa.String(length=20), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cv_version_id'], ['cv_versions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vacancy_id'], ['vacancies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vacancy_match_analyses_created_at'), 'vacancy_match_analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_vacancy_match_analyses_input_hash'), 'vacancy_match_analyses', ['input_hash'], unique=False)
    op.create_index('ix_vacancy_match_analyses_queue', 'vacancy_match_analyses', ['status', 'started_at', 'created_at'], unique=False)
    op.create_index(op.f('ix_vacancy_match_analyses_user_id'), 'vacancy_match_analyses', ['user_id'], unique=False)
    op.create_index('ix_vacancy_match_analyses_vacancy_created', 'vacancy_match_analyses', ['vacancy_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_vacancy_match_analyses_vacancy_id'), 'vacancy_match_analyses', ['vacancy_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vacancy_match_analyses_vacancy_id'), table_name='vacancy_match_analyses')
    op.drop_index('ix_vacancy_match_analyses_vacancy_created', table_name='vacancy_match_analyses')
    op.drop_index(op.f('ix_vacancy_match_analyses_user_id'), table_name='vacancy_match_analyses')
    op.drop_index('ix_vacancy_match_analyses_queue', table_name='vacancy_match_analyses')
    op.drop_index(op.f('ix_vacancy_match_analyses_input_hash'), table_name='vacancy_match_analyses')
    op.drop_index(op.f('ix_vacancy_match_analyses_created_at'), table_name='vacancy_match_analyses')
    op.drop_table('vacancy_match_analyses')
    # ### end Alembic commands ###
